changed env

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -34,14 +34,22 @@ jobs:
     - name: Terraform Apply
       run: terraform apply -auto-approve
 
-      
+
     - name: Get EC2 Public IP and create hosts.ini file for Ansible
       run: |
-        EC2_PUBLIC_IP=$(terraform output -raw instance_public_ip | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
+        EC2_PUBLIC_IP=$(terraform output -raw instance_public_ip | tr -d '[:space:]')
+    
         if [ -z "$EC2_PUBLIC_IP" ]; then
-        echo "Error: EC2_PUBLIC_IP is not set."
-        exit 1
+          echo "Error: EC2_PUBLIC_IP is not set."
+          exit 1
         fi
+    
+        # Ensure valid format (IPv4 address)
+        if ! echo "$EC2_PUBLIC_IP" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'; then
+          echo "Error: Invalid IP format '$EC2_PUBLIC_IP'"
+          exit 1
+        fi
+
         echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV  # Save for next steps
 
         echo "[web_servers]" > hosts.ini
